### ISSUE TITLE
Controller bug on FireTV stick OS 7.x.x 

### ISSUE THREAD

**Issue by vmansur** [libretro/docs#756] opened 2022-08-01 12:56 UTC
**Describe the bug**
 Retroarch for some reason understands that the fire stick's remote controller is a gamepad controller, and always adds it as controller 1.

- If you start retroarch using remote-controller: it will assign the remote-controller as 1 controller, so when loading a rom, the gamepad controller will be assigned to 2 - and it's not going to work. -- If you manage to go to the settings then, and add the gamepad as 1. Now anything works anymore. Like not even remote-controller nor gamepad will navigate correctly on menus.

- If you start retroarch from the gamepad: It will assign the gamepad as 1 controller. Mostly the default controller configuration will work, but the start/select buttons. And if you go to settings and try to configure it correctly, now you screwed the gamepad and nothing works again.

- If you start retroarch with gamepad, configure the controller before entering a rom. It should work. But if you touch the remote controller, RA will assign it to 1 controller and you will mess all the controller configurations and nothing works correctly anymore. If you still manage to go to configurations and configure it again, you'll be able to use the D-pad but not the A/B/X/Y buttons.

- Among other different behaviour if you try different orders/configurations 

**Expected behavior/changes**
- Controller should not lose configuration when entering a an emulador. Auto-detect works well in many other environements, not on Fire Tv Stick with Fire OS > 7.x.x
- Same controller configuration should work both for retroarch, and emulator. 
- Controller should not change configuration when using the amazon's remote controller. 

**Additional context**
- Using most updated available version of FireOS
- Tested with PS4 and Gamesir G3s controllers, same issue for both.
- On fire tv menus both controllers are working perfectly well.
- Tested with some standalone emulators, and I don't have those issues on them.
- tested with several versions of retroarch, 1.9.x, 1.10.x, nightly, stable, google play vesion, aptoide version, even downloading apk from official website. All of them gave me same issues.
- Tested on Xiaomi mi stick with android 9, everything works very well with zero configuration. I couldn't reproduce this issue, seems to me that this is a fire tv stick issue

more information:
https://www.reddit.com/r/RetroArch/comments/w9lfi1/amazon_fire_tv_stick_4k_max_controller_issues/

**Comment by fpscan** [comment] 2022-08-01 20:39
While we are trying to bring RetroArch to Amazon AppStore, we had to make sure it is okay with store rules for Games. So it is not a program because Games has different resource distribution. Since we go with Games we had to make remote is usable. So I provided few layout to Amazon. Amazon didn't liked the way it is so we had to make sure the app usable with remote. So we talked in here: https://github.com/libretro/retroarch-joypad-autoconfig/issues/777 then merged this: https://github.com/libretro/retroarch-joypad-autoconfig/pull/778 

I am not sure the issue is just related to Amazon release or overall apk release but our hands are tied for that particulur release, because we want to make it best possible experience across fire devices meanwhile we don't want to poke around to get ourselves kicked from store.

**Comment by vmansur** [comment] 2022-08-02 18:06
Hi, thank you for your reply!
I believe this is not an amazon-store relase issue, since even downloading the apk from retroarch website and sideloading it to the fire stick, the problem is exactly the same. 
I also teste the Aptoide and Google play store versions. All the same issue

**Comment by gouchi** [comment] 2023-01-23 16:16
@vmansur I think this issue should be in [RetroArch issue tracker](https://github.com/libretro/RetroArch/issues) not documentation ?

Thank you.

**Closed as completed** 2023-04-28 20:26 UTC
Labels: bug
